<?php

  $GLOBALS['hobbsfmt'] = "%04.1f";
  $GLOBALS['classcode'] = array("null","ASEL","ASES","AMES","AMEL","Sim","Glider");

  $GLOBALS['classname'] = array("null",
                                "Airplane, Single Engine Land",
                                "Airplane, Single Engine Sea",
                                "Airplane, Multi Engine Land",
                                "Airplane, Multi Engine Land",
                                "Simulator",
                                "Glider");

  $GLOBALS['statusgoals']= array (
                         "Silver:30:30",
                         "Gold:60:60",
                         "Platinum:90:90"
                        );

?>
