<!-- $Id$ -->

  <div id="footer">

   <p class="fineprint">
    Always maintain a traditional, written pilot logbook.
    <br />
    Not valid for endorsements, ratings, flight currency, certification, flight planning, or any operational purpose.
    <br />
    <a href="http://www.cuckoo.com/daniel/software/lol/">Logbook Online</a> v<?php print $GLOBALS['lolversion']; ?>
    &copy; Copyright 2002-<?php print date ("Y"); ?> Daniel Baker and David McNett.  All Rights Reserved.
   </p>

  </div>

 </body>
</html>
